# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dcSVD <- function(X) {
    .Call(`_TR_dcSVD`, X)
}

sparseXinvL <- function(X, L) {
    .Call(`_TR_sparseXinvL`, X, L)
}

sparseinvLX <- function(L, X) {
    .Call(`_TR_sparseinvLX`, L, X)
}

